/*
*
* Kuran Browser
* Author	: Mert Can Yalhi (http://mert.co)
* Date		: 30-Oct-2011
*
* Copyright (c) 2011 Mert Can Yalhi
* Dual licensed under the MIT or GPL Version 2 licenses.
* http://jquery.org/license
*
*/


jQuery.fn.positionAncestor = function (a) { var b = 0, c = 0; this.each(function () { var d = $(this).closest(a); if (d.length) { var e = $(this), f = e.offset().left - parseInt(e.css("marginLeft"), 10), e = e.offset().top - parseInt(e.css("marginTop"), 10), g = d.offset().left + parseInt(d.css("borderLeftWidth"), 10), d = d.offset().top + parseInt(d.css("borderTopWidth"), 10); b = f - g; c = e - d; return !1 } }); return { left: b, top: c } };

var selectedTr, selectedAr, CurrentSure, CurrentAyet, CurrentAyetPlayer, NewSure = !1, isClick = !1, ended = !1, newLineHeightTR = 0, newLineHeightAR = 0, newFontSizeTR = 0, newFontSizeAR = 0, newLineHeightNumberTR = 0, newLineHeightNumberAR = 0, newFontSizeNumberTR = 0, newFontSizeNumberAR = 0, newFontSizeBesmele = 0, newLineHeightBesmele = 0, translateLanguageId = 1, hizliErisimVisible = !0, lastSelected = ""; function isNumber(a) { return !isNaN(parseFloat(a)) && isFinite(a) }

$(document).ready(function () {
    document.onmouseup = mouseup; $('input[title!=""]').hint(); GetCatalog(); $("#jquery_jplayer_1").jPlayer({
        ready: function () {
            var a = $("#SelectRecitation option:selected").val(); CurrentAyetPlayer = CurrentAyet; NewSure = !0; 1 == CurrentAyet && (CurrentAyetPlayer = 0); $(this).jPlayer("setMedia", {
                oga: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".ogg", m4a: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".m4a", mp3: "http://webdosya.diyanet.gov.tr/kuran/Sound/" +
                a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".mp3"
            })
        }, swfPath: "js", supplied: "oga,m4a,mp3", wmode: "window", ended: function () { GoToNext(); ended || $(this).jPlayer("play") }
    }); $("#InputFontSize").val(15); $.browser.msie && 9 > $.browser.version && alert("Kur'an-\u0131 Kerim portal\u0131n\u0131 verimli kullanabilmek i\u00e7in web taray\u0131c\u0131n\u0131z\u0131 Internet Explorer 9/Firefox 11 veya daha g\u00fcncel bir s\u00fcr\u00fcme g\u00fcncellemeniz gerekmektedir"); $.browser.mozilla && "11.0" > $.browser.version && alert("Kur'an-\u0131 Kerim portal\u0131n\u0131 verimli kullanabilmek i\u00e7in web taray\u0131c\u0131n\u0131z\u0131 Internet Explorer 9/Firefox 11 veya daha g\u00fcncel bir s\u00fcr\u00fcme g\u00fcncellemeniz gerekmektedir")
});
function getSelectedText() { return window.getSelection ? window.getSelection() : document.selection ? document.selection.createRange().text : "" } function contextMenuWorkAr(a) { switch (a) { case "doCopy": a = getSelectedText(); "" != a && " " != a ? copyToClipboard(a) : copyToClipboard(lastSelected); break; case "doSearchSelected": a = getSelectedText(), "" != a && " " != a ? $("#InputSearch").val('"' + a + '"') : $("#InputSearch").val('"' + lastSelected + '"'), $("#Search-Button").click() } }
function contextMenuWorkTr(a) { switch (a) { case "doCopy": a = getSelectedText(); "" != a && " " != a ? copyToClipboard(a) : copyToClipboard(lastSelected); break; case "doSearchSelected": a = getSelectedText(), "" != a && " " != a ? $("#InputSearch").val('"' + a + '"') : $("#InputSearch").val('"' + lastSelected + '"'), $("#Search-Button").click() } }
function copyToClipboard(a) { if (window.clipboardData) window.clipboardData.setData("text", a); else { var b = document.getElementById("divclipboardswf"); null == b && (b = document.createElement("div"), b.setAttribute("name", "divclipboardswf"), b.setAttribute("id", "divclipboardswf"), document.body.appendChild(b)); b.innerHTML = '<embed src="clipboard.swf" FlashVars="clipboard=' + encodeURIComponent(a) + '" width="0" height="0" type="application/x-shockwave-flash"></embed>' } return !1 }
function mouseup() { var a = getSelectedText(); "" != a && " " != a && (lastSelected = a + " ", lastSelected = $.trim(lastSelected)) } $("#HizliErisim_Control").click(function () { hizliErisimVisible ? ($("#HizliErisimContainer").animate({ bottom: "-60px" }, "slow"), $("#HizliErisim_Control").attr("src", "/hizlierisim/show.gif"), hizliErisimVisible = !1) : ($("#HizliErisimContainer").animate({ bottom: "0px" }, "slow"), $("#HizliErisim_Control").attr("src", "/hizlierisim/hide.gif"), hizliErisimVisible = !0) }); FillCuz();
if (null == $.cookie("Ayet")) { var SureId = 1, AyetId = 1, AyetName = SureId + ":" + AyetId; $.cookie("Ayet", AyetName, { expires: 60, path: "/" }) } else var temp = $.cookie("Ayet").split(":"), SureId = temp[0], AyetId = temp[1]; GoToAyet(SureId, AyetId); CurrentSure = SureId; CurrentAyet = AyetId;
if (null == $.cookie("KuranStyle")) UpdateStyleCookie(); else { temp = $.cookie("KuranStyle").split(":"); try { newLineHeightTR = temp[0], newLineHeightAR = temp[1], newFontSizeTR = temp[2], newFontSizeAR = temp[3], newLineHeightNumberTR = temp[4], newLineHeightNumberAR = temp[5], newFontSizeNumberTR = temp[6], newFontSizeNumberAR = temp[7], newFontSizeBesmele = temp[8], newLineHeightBesmele = temp[9] } catch (err) { } } $("#SelectMeal option[value='" + translateLanguageId + "']").attr("selected", "selected");
function UpdateStyleCookie() { $.cookie("KuranStyle", newLineHeightTR + ":" + newLineHeightAR + ":" + newFontSizeTR + ":" + newFontSizeAR + ":" + newLineHeightNumberTR + ":" + newLineHeightNumberAR + ":" + newFontSizeNumberTR + ":" + newFontSizeNumberAR + ":" + newFontSizeBesmele + ":" + newLineHeightBesmele, { expires: 60, path: "/" }) } $("#LoadingDiv").hide().ajaxStart(function () { $(this).show() }).ajaxStop(function () { $(this).hide() }); $.address.strict(!1);
$.address.change(function (a) {
    if (1 < a.value.length) if ("egitim" == a.value.replace("/", "")) $("#MainTab").tabs("option", "selected", 5); else if ("tefsir" == a.value.replace("/", "")) $("#MainTab").tabs("option", "selected", 4); else if ("yardim" == a.value.replace("/", "")) $("#MainTab").tabs("option", "selected", 8); else if ("hakkinda" == a.value.replace("/", "")) $("#MainTab").tabs("option", "selected", 7); else if ("kutuphane" == a.value.replace("/", "")) $("#MainTab").tabs("option", "selected", 6); else if ("fihrist" == a.value.replace("/",
    "")) $("#MainTab").tabs("option", "selected", 2); else {
        var b = a.value.replace("/", "").split(":"), a = b[0], b = b[1]; $.cookie("Ayet", a + ":" + b, { expires: 60, path: "/" }); var c = "ar_" + a + "-" + b, d = c; 1 == $("#MainTab").tabs("option", "selected") && (d = "tr_" + a + "-" + b); 0 < !$("#" + c).length ? GoToAyet(a, b) : isClick || $("#" + d).trigger("click"); CurrentSure = a; CurrentAyet = b; c = $("#SelectRecitation option:selected").val(); CurrentAyetPlayer = b; 1 == CurrentAyet && (CurrentAyetPlayer = 0); UpdateFontSize(); $("#jquery_jplayer_1").jPlayer("setMedia", {
            oga: "http://webdosya.diyanet.gov.tr/kuran/Sound/" +
            c + "/" + a + "_" + CurrentAyetPlayer + ".ogg", m4a: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + c + "/" + a + "_" + CurrentAyetPlayer + ".m4a", mp3: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + c + "/" + a + "_" + CurrentAyetPlayer + ".mp3"
        })
    }
}); $("#SelectMeal").change(function () { translateLanguageId = $(this).attr("value"); GoToAyet(CurrentSure, CurrentAyet) }); $("#SelectSure").change(function () { var a = $(this).attr("value").split(":"), b = a[0], a = a[1]; FillAyet(b); b != CurrentSure && $.address.value(b + ":" + a) });
$("#SelectAyet").change(function () { var a = $(this).attr("value").split(":"); $.address.value(a[0] + ":" + a[1]) }); $("#SelectCuz").change(function () { var a = $(this).attr("value").split(":"); $.address.value(a[0] + ":" + a[1]) }); $("#InputSayfa").change(function () { var a = $("#InputSayfa").val(); 1 > a ? $("#InputSayfa").val(1) : 604 < a && $("#InputSayfa").val(604); a = $("#InputSayfa").val(); a != $("#Page-Number-Turkish").html() && $.address.value(AyetPages[a][0] + ":" + AyetPages[a][1]) });
$("#SelectRecitation").change(function () { var a = $("#SelectRecitation option:selected").val(); $("#jquery_jplayer_1").jPlayer("setMedia", { oga: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".ogg", m4a: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".m4a", mp3: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".mp3" }) });
$("#SelectFont").change(function () { var a = "@font-face {                      font-family: KuranFont;                 src: url('" + $(this).attr("value") + "'); }                                       "; addDeclaration(a); FixHeights() }); function addDeclaration(a) { if (document.createStyleSheet) { var b = document.createStyleSheet(); b.cssText = a } else b = document.createElement("style"), b.textContent = a, document.getElementsByTagName("head")[0].appendChild(b) }
function UpdateFontSize() { UpdateFontSizeElementAR(".Ayet-Text"); UpdateLineHeightElementAR(".Ayet-Text"); UpdateFontSizeElementTR(".Ayet-Text-Turkish"); UpdateLineHeightElementTR(".Ayet-Text-Turkish"); UpdateFontSizeNumberAR(".Ayet-Number"); UpdateLineHeightNumberAR(".Ayet-Number"); UpdateFontSizeNumberTR(".Ayet-Number-Turkish"); UpdateLineHeightNumberTR(".Ayet-Number-Turkish"); UpdateFontSizeBesmele(".Besmele"); UpdateLineHeightBesmele(".Besmele"); FixHeights() }
function UpdateFontSizeElementTR(a) { 0 < newFontSizeTR && $(a).css("font-size", newFontSizeTR + "px"); return !1 } function UpdateFontSizeElementAR(a) { 0 < newFontSizeAR && $(a).css("font-size", newFontSizeAR + "px"); return !1 } function UpdateLineHeightElementTR(a) { 0 < newLineHeightTR && $(a).css("line-height", newLineHeightTR + "px"); return !1 } function UpdateLineHeightElementAR(a) { 0 < newLineHeightAR && $(a).css("line-height", newLineHeightAR + "px"); return !1 }
function UpdateFontSizeNumberTR(a) { 0 < newFontSizeNumberTR && (30 < newFontSizeNumberTR ? $(a).css("font-size", "30px") : $(a).css("font-size", newFontSizeNumberTR + "px")); return !1 } function UpdateFontSizeNumberAR(a) { 0 < newFontSizeNumberAR && (30 < newFontSizeNumberAR ? $(a).css("font-size", "30px") : $(a).css("font-size", newFontSizeNumberAR + "px")); return !1 } function UpdateFontSizeBesmele(a) { 0 < newFontSizeBesmele && (25 < newFontSizeBesmele ? $(a).css("font-size", "25px") : $(a).css("font-size", newFontSizeBesmele + "px")); return !1 }
function UpdateLineHeightNumberTR(a) { 0 < newLineHeightNumberTR && $(a).css("line-height", newLineHeightNumberTR + "px"); return !1 } function UpdateLineHeightNumberAR(a) { 0 < newLineHeightNumberAR && $(a).css("line-height", newLineHeightNumberAR + "px"); return !1 } function UpdateLineHeightBesmele(a) { 0 < newLineHeightBesmele && $(a).css("line-height", newLineHeightBesmele + "px"); return !1 }
function IncreaseFontSize() { IncreaseFontSizeElementAR(".Ayet-Text"); IncreaseLineHeightElementAR(".Ayet-Text"); IncreaseFontSizeElementTR(".Ayet-Text-Turkish"); IncreaseLineHeightElementTR(".Ayet-Text-Turkish"); IncreaseFontSizeNumberAR(".Ayet-Number"); IncreaseLineHeightNumberAR(".Ayet-Number"); IncreaseFontSizeNumberTR(".Ayet-Number-Turkish"); IncreaseLineHeightNumberTR(".Ayet-Number-Turkish"); IncreaseFontSizeBesmele(".Besmele"); IncreaseLineHeightBesmele(".Besmele"); FixHeights(); UpdateStyleCookie() }
function IncreaseFontSizeElementTR(a) { var b = $(a).css("font-size"); newFontSizeTR = parseFloat(b, 10) + 1; $(a).css("font-size", newFontSizeTR + "px"); $("#InputFontSize").val(parseInt(newFontSizeTR)); return !1 } function IncreaseFontSizeElementAR(a) { var b = $(a).css("font-size"); newFontSizeAR = parseFloat(b, 10) + 1; $(a).css("font-size", newFontSizeAR); $("#InputFontSize").val(parseInt(newFontSizeAR)); return !1 }
function IncreaseLineHeightElementTR(a) { var b = $(a).css("line-height"); newLineHeightTR = parseInt(b, 10) + 1; $(a).css("line-height", newLineHeightTR + "px"); return !1 } function IncreaseLineHeightElementAR(a) { var b = $(a).css("line-height"); newLineHeightAR = parseInt(b, 10) + 1; $(a).css("line-height", newLineHeightAR + "px"); return !1 }
function IncreaseFontSizeNumberTR(a) { var b = $(a).css("font-size"), b = parseFloat(b, 10); 30 < newFontSizeNumberTR ? (newFontSizeNumberTR += 1, $(a).css("font-size", "30px")) : (newFontSizeNumberTR = b + 1, $(a).css("font-size", newFontSizeNumberTR + "px")); return !1 } function IncreaseFontSizeNumberAR(a) { var b = $(a).css("font-size"), b = parseFloat(b, 10); 30 < newFontSizeNumberAR ? (newFontSizeNumberAR += 1, $(a).css("font-size", "30px")) : (newFontSizeNumberAR = b + 1, $(a).css("font-size", newFontSizeNumberAR + "px")); return !1 }
function IncreaseFontSizeBesmele(a) { var b = $(a).css("font-size"), b = parseFloat(b, 10); 25 < newFontSizeBesmele ? (newFontSizeBesmele += 1, $(a).css("font-size", "25px")) : (newFontSizeBesmele = b + 1, $(a).css("font-size", newFontSizeBesmele + "px")); return !1 } function IncreaseLineHeightBesmele(a) { var b = $(a).css("line-height"); newLineHeightBesmele = parseInt(b, 10) + 1; $(a).css("line-height", newLineHeightBesmele + "px"); return !1 }
function IncreaseLineHeightNumberTR(a) { var b = $(a).css("line-height"); newLineHeightNumberTR = parseInt(b, 10) + 1; $(a).css("line-height", newLineHeightNumberTR + "px"); return !1 } function IncreaseLineHeightNumberAR(a) { var b = $(a).css("line-height"); newLineHeightNumberAR = parseInt(b, 10) + 1; $(a).css("line-height", newLineHeightNumberAR + "px"); return !1 }
function DecreaseFontSize() { DecreaseFontSizeElementAR(".Ayet-Text"); DecreaseLineHeightElementAR(".Ayet-Text"); DecreaseFontSizeElementTR(".Ayet-Text-Turkish"); DecreaseLineHeightElementTR(".Ayet-Text-Turkish"); DecreaseFontSizeNumberAR(".Ayet-Number"); DecreaseLineHeightNumberAR(".Ayet-Number"); DecreaseFontSizeNumberTR(".Ayet-Number-Turkish"); DecreaseLineHeightNumberTR(".Ayet-Number-Turkish"); DecreaseFontSizeBesmele(".Besmele"); DecreaseLineHeightBesmele(".Besmele"); FixHeights(); UpdateStyleCookie() }
function DecreaseFontSizeElementTR(a) { var b = $(a).css("font-size"); newFontSizeTR = parseFloat(b, 10) - 1; $(a).css("font-size", newFontSizeTR + "px"); $("#InputFontSize").val(parseInt(newFontSizeTR)); return !1 } function DecreaseFontSizeElementAR(a) { var b = $(a).css("font-size"); newFontSizeAR = parseFloat(b, 10) - 1; $(a).css("font-size", newFontSizeAR); return !1 } function DecreaseLineHeightElementTR(a) { var b = $(a).css("line-height"); newLineHeightTR = parseInt(b, 10) - 1; $(a).css("line-height", newLineHeightTR + "px"); return !1 }
function DecreaseLineHeightElementAR(a) { var b = $(a).css("line-height"); newLineHeightAR = parseInt(b, 10) - 1; $(a).css("line-height", newLineHeightAR + "px"); return !1 } function DecreaseFontSizeNumberTR(a) { var b = $(a).css("font-size"), b = parseFloat(b, 10); 30 < newFontSizeNumberTR ? newFontSizeNumberTR -= 1 : (newFontSizeNumberTR = b - 1, $(a).css("font-size", newFontSizeNumberTR + "px")); return !1 }
function DecreaseFontSizeNumberAR(a) { var b = $(a).css("font-size"), b = parseFloat(b, 10); 30 < newFontSizeNumberAR ? newFontSizeNumberAR -= 1 : (newFontSizeNumberAR = b - 1, $(a).css("font-size", newFontSizeNumberAR + "px")); return !1 } function DecreaseFontSizeBesmele(a) { var b = $(a).css("font-size"), b = parseFloat(b, 10); 25 < newFontSizeBesmele ? newFontSizeBesmele -= 1 : (newFontSizeBesmele = b - 1, $(a).css("font-size", newFontSizeBesmele + "px")); return !1 }
function DecreaseLineHeightBesmele(a) { var b = $(a).css("line-height"); newLineHeightBesmele = parseInt(b, 10) - 1; $(a).css("line-height", newLineHeightBesmele + "px"); return !1 } function DecreaseLineHeightNumberTR(a) { var b = $(a).css("line-height"); newLineHeightNumberTR = parseInt(b, 10) - 1; $(a).css("line-height", newLineHeightNumberTR + "px"); return !1 }
function DecreaseLineHeightNumberAR(a) { var b = $(a).css("line-height"); newLineHeightNumberAR = parseInt(b, 10) - 1; $(a).css("line-height", newLineHeightNumberAR + "px"); return !1 }
$("#Search-Button").click(function () {
    var a = new Date, b = jQuery.trim($("#InputSearch").val()); "" != b && ($("#MainTab").tabs("enable", 1), $("#MainTab").tabs("option", "selected", 1), $.post("KuranHandler.ashx?l=" + $("#SelectMeal").attr("value") + "&search=" + encodeURIComponent(b), function (c) {
        var d = (new Date - a) / 1E3; $("#Search-Result").empty(); $("#Search-Text").html("Aranan: <b>" + b + "</b>"); $("#Search-Result-Count").html("<b>" + c.length + "</b> sonu\u00e7 (" + d + " saniye)"); var e = '<ul class="SearchResultList">'; $.each(c,
        function (a, b) { e += '<li class="SearchResultListItem"><div onclick=\'javascript:GetSearchResult(' + b.SureId + "," + b.AyetId + "," + b.LanguageId + ")' class='Search-Result-Item'><span class='Search-Result-Item-Header'>" + b.SureId + ". Sure (" + b.SureName + " Suresi), " + b.AyetId + ". Ayet</span><br /><span class='Search-Result-Item-Content'>" + b.AyetText + "</span></div></li>" }); e += "</ul>"; $("#Search-Result").html(e); $(".SearchResultList").easyPaginate({ step: 10 })
    }, "json"))
});
function GoToNext() {
    ended = !1; if (114 == CurrentSure && 6 == CurrentAyet) ended = !0; else if (AyetCount[CurrentSure] == CurrentAyet) CurrentSure++, CurrentAyet = 1; else if (0 != CurrentAyetPlayer) CurrentAyet++; else {
        CurrentAyetPlayer++; var a = $("#SelectRecitation option:selected").val(); $("#jquery_jplayer_1").jPlayer("setMedia", {
            oga: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".ogg", m4a: "http://webdosya.diyanet.gov.tr/kuran/Sound/" + a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".m4a", mp3: "http://webdosya.diyanet.gov.tr/kuran/Sound/" +
            a + "/" + CurrentSure + "_" + CurrentAyetPlayer + ".mp3"
        })
    } ended || $.address.value(CurrentSure + ":" + CurrentAyet)
} function NextPage() { var a = $("#InputSayfa").val(); a++; 1 > a ? $("#InputSayfa").val(1) : 604 < a && $("#InputSayfa").val(604); a != $("#Page-Number-Turkish").html() && $.address.value(AyetPages[a][0] + ":" + AyetPages[a][1]) }
function PreviousPage() { var a = $("#InputSayfa").val(); a--; 1 > a ? $("#InputSayfa").val(1) : 604 < a && $("#InputSayfa").val(604); a != $("#Page-Number-Turkish").html() && $.address.value(AyetPages[a][0] + ":" + AyetPages[a][1]) } function GetSearchResult(a, b, c) { $.address.value(a + ":" + b); 1 == c ? $("#MainTab").tabs("option", "selected", 1) : 2 == c && $("#MainTab").tabs("option", "selected", 0); $("#MainTab").tabs("option", "selected", 0) }
function GoToAyet(a, b) {
    $.cookie("Ayet", a + ":" + b, { expires: 60, path: "/" }); $.post("KuranHandler.ashx?l=ar&a=" + a + ":" + b, {}, function (c) {
        $("#Kuran").html(c); AyetArabicTooltip(); AyetArabicClick(); $.post("KuranHandler.ashx?l=tefsir&lid=" + translateLanguageId + "&a=" + a + ":" + b, {}, function (a) { $("#KuranTefsir").html(a); $(".Ayet-Tefsir").contextMenu({ menu: "ContextMenu" }, function (a, b, c) { contextMenuWorkTr(a, b, c) }) }); $.post("KuranHandler.ashx?lid=" + translateLanguageId + "&a=" + a + ":" + b, {}, function (c) {
            $("#KuranTurkish").html(c);
            AyetTurkishTooltip(); AyetTurkishClick(); $("#InputSayfa").val(GetAyetPage(a, b)); $("#ar_" + a + "-" + b).trigger("click"); SelectCuz(a, b); UpdateFontSize(); $(".Ayet-Turkish").contextMenu({ menu: "ContextMenu" }, function (a, b, c) { contextMenuWorkTr(a, b, c) })
        }); $(".Ayet").contextMenu({ menu: "ContextMenu" }, function (a, b, c) { contextMenuWorkAr(a, b, c) })
    })
} function FillAyet(a) { $("#SelectAyet").empty(); for (var b = 1; b <= AyetCount[a]; b++) $("#SelectAyet").append('<option value="' + a + ":" + b + '">' + b + "</option>") }
function FillCuz() { $("#SelectCuz").empty(); for (var a = 1; 30 >= a; a++) $("#SelectCuz").append('<option value="' + CuzStart[a] + '">C\u00fcz ' + a + "</option>") }
function SelectCuz(a, b) {
    for (var c = 1; 30 >= c; c++) {
        var d = parseInt(CuzStart[c].split(":")[0]), e = parseInt(CuzStart[c].split(":")[1]), f = parseInt(CuzEnd[c].split(":")[0]), g = parseInt(CuzEnd[c].split(":")[1]); if (a >= d && a <= f) if (a == d) if (f == a) { if (b >= e && b <= g) { $("#SelectCuz option[value='" + CuzStart[c] + "']").attr("selected", "selected"); break } } else { if (b >= e) { $("#SelectCuz option[value='" + CuzStart[c] + "']").attr("selected", "selected"); break } } else if (a == f) {
            if (b <= g) {
                $("#SelectCuz option[value='" + CuzStart[c] + "']").attr("selected",
                "selected"); break
            }
        } else { $("#SelectCuz option[value='" + CuzStart[c] + "']").attr("selected", "selected"); break }
    }
} function GetAyetPage(a, b) { for (var c = 1; 604 >= c; c++) { var d = AyetPages[c][0], e = AyetPages[c][1], f = AyetPages[c + 1][0], g = AyetPages[c + 1][1]; if (d == f) { if (a == d && b >= e && b < g) return c } else if (a >= d && a <= f) if (a == d) { if (b >= e) return c } else if (a == f) { if (b < g) return c } else return c } }
function AyetArabicTooltip() { $(".Ayet").each(function () { tooltipId = "tr_" + $(this).attr("id").split("_")[1]; $(this).tooltip({ tip: "#tooltip_" + tooltipId, effect: "slide" }).hover(function () { selectedTr != "#" + this.id && selectedAr != "#" + this.id && $(this).animate({ backgroundColor: "#ede4b4" }, "fast") }, function () { selectedTr != "#" + this.id && selectedAr != "#" + this.id && $(this).animate({ backgroundColor: "#fff4da" }, "fast") }) }) }
function AyetTurkishTooltip() { $(".Ayet-Turkish").each(function () { tooltipId = "ar_" + $(this).attr("id").split("_")[1]; $(this).tooltip({ tip: "#tooltip_" + tooltipId, effect: "slide" }).hover(function () { selectedTr != "#" + this.id && selectedAr != "#" + this.id && $(this).animate({ backgroundColor: "#ede4b4" }, "fast") }, function () { selectedTr != "#" + this.id && selectedAr != "#" + this.id && $(this).animate({ backgroundColor: "#fff4da" }, "fast") }) }) }
function AyetArabicClick() {
    $(".Ayet").click(function () {
        isClick = !0; null != selectedTr && selectedTr != "#" + this.id && $(selectedTr).animate({ backgroundColor: "#fff4da" }, "slow"); null != selectedAr && selectedAr != "#" + this.id && $(selectedAr).animate({ backgroundColor: "#fff4da" }, "slow"); for (var a = this.id.split("_")[1].split("-"), b = a[0], c = a = a[1]; !$("#tr_" + b + "-" + c).length;) c--; var d = "#tr_" + b + "-" + c, e = "#ar_" + b + "-" + a; $(d).animate({ backgroundColor: "#ebdd9a" }, "slow"); $(e).animate({ backgroundColor: "#ebdd9a" }, "slow"); selectedTr =
        d; selectedAr = e; d = $("#MainTab").tabs("option", "selected"); 0 == d ? $.scrollTo($(e), 800, { axis: "y", offset: { top: -50 } }) : 4 == d && (e = "#tefsir_" + b + "-" + a, 0 != $(e).length && $.scrollTo($(e), 800, { axis: "y", offset: { top: 0 } })); $("#Kuran-Selected-Original").html("<b>" + $("#tooltip_ar_" + b + "-" + a + " .Tooltip-Header-Arabic").html() + "</b><br><span id='Kuran-Selected-Original-Text'>" + $("#tooltip_ar_" + b + "-" + a + " .Tooltip-Content-Arabic").html() + "</span><br><br>"); $("#Kuran-Selected-Translate").html("<b>" + $("#tooltip_tr_" + b + "-" + c + " .Tooltip-Header").html() +
        "</b><br><span id='Kuran-Selected-Translate-Text'>" + $("#tooltip_tr_" + b + "-" + c + " .Tooltip-Content").html() + "</span>"); $("#Kuran-Selected-Turkish-Original").html("<b>" + $("#tooltip_tr_" + b + "-" + c + " .Tooltip-Header").html() + "</b><br><span id='Kuran-Selected-Turkish-Original-Text'>" + $("#tooltip_tr_" + b + "-" + c + " .Tooltip-Content").html() + "</span><br><br>"); $("#Kuran-Selected-Turkish-Translate").html("<b>" + $("#tooltip_ar_" + b + "-" + a + " .Tooltip-Header-Arabic").html() + "</b><br><span id='Kuran-Selected-Turkish-Translate-Text'>" +
        $("#tooltip_ar_" + b + "-" + a + " .Tooltip-Content-Arabic").html() + "</span>"); $("#SelectSure option[value='" + b + ":1']").attr("selected", "selected"); FillAyet(b); $("#SelectAyet option[value='" + b + ":" + a + "']").attr("selected", "selected"); $.address.value(b + ":" + a); isClick = !1
    })
}
function AyetTurkishClick() {
    $(".Ayet-Turkish").click(function () {
        isClick = !0; null != selectedTr && selectedTr != "#" + this.id && $(selectedTr).animate({ backgroundColor: "#fff4da" }, "slow"); null != selectedAr && selectedAr != "#" + this.id && $(selectedAr).animate({ backgroundColor: "#fff4da" }, "slow"); for (var a = this.id.split("_")[1].split("-"), b = a[0], c = a = a[1]; !$("#tr_" + b + "-" + c).length;) c--; var d = "#tr_" + b + "-" + a, e = "#ar_" + b + "-" + c; $(d).animate({ backgroundColor: "#ebdd9a" }, "slow"); $(e).animate({ backgroundColor: "#ebdd9a" }, "slow");
        selectedTr = d; selectedAr = e; e = $("#MainTab").tabs("option", "selected"); 0 == e ? $.scrollTo($(d), 800, { axis: "y", offset: { top: -50 } }) : 4 == e && (d = "#tefsir_" + b + "-" + a, 0 != $(d).length && $.scrollTo($(d), 800, { axis: "y", offset: { top: 0 } })); $("#Kuran-Selected-Original").html("<b>" + $("#tooltip_ar_" + b + "-" + c + " .Tooltip-Header-Arabic").html() + "</b><br><span id='Kuran-Selected-Original-Text'>" + $("#tooltip_ar_" + b + "-" + c + " .Tooltip-Content-Arabic").html() + "</span><br><br>"); $("#Kuran-Selected-Translate").html("<b>" + $("#tooltip_tr_" +
        b + "-" + a + " .Tooltip-Header").html() + "</b><br><span id='Kuran-Selected-Translate-Text'>" + $("#tooltip_tr_" + b + "-" + a + " .Tooltip-Content").html() + "</span>"); $("#Kuran-Selected-Turkish-Original").html("<b>" + $("#tooltip_tr_" + b + "-" + a + " .Tooltip-Header").html() + "</b><br><span id='Kuran-Selected-Turkish-Original-Text'>" + $("#tooltip_tr_" + b + "-" + a + " .Tooltip-Content").html() + "</span><br><br>"); $("#Kuran-Selected-Turkish-Translate").html("<b>" + $("#tooltip_ar_" + b + "-" + c + " .Tooltip-Header-Arabic").html() + "</b><br><span id='Kuran-Selected-Turkish-Translate-Text'>" +
        $("#tooltip_ar_" + b + "-" + c + " .Tooltip-Content-Arabic").html() + "</span>"); $("#SelectSure option[value='" + b + ":1']").attr("selected", "selected"); FillAyet(b); $("#SelectAyet option[value='" + b + ":" + a + "']").attr("selected", "selected"); $.address.value(b + ":" + a); isClick = !1
    })
}
function FixHeights() {
    if ($("#Pointer-Secde-AyetId").length) { var a = $("#Pointer-Secde-AyetId").text().split("-"), b = a[0], a = a[1]; for ($("#ar_" + b + "-" + a).length && $(".Kuran-Secde").css("top", $("#ar_" + b + "-" + a + " span .Ayet-Number").positionAncestor("#Kuran").top - 50 + "px") ; !$("#tr_" + b + "-" + a).length && !(a--, 0 == a) ;); $("#tr_" + b + "-" + a).length && $(".Kuran-Secde-Turkish").css("top", $("#tr_" + b + "-" + a + " span .Ayet-Number-Turkish").positionAncestor("#KuranTurkish").top - 55 + "px") } $("#Kuran-Text").height(""); $("#Kuran-Text-Turkish").height("");
    b = $("#Kuran-Text").height(); a = $("#Kuran-Text-Turkish").height(); null != b && null != a && (b > a ? $("#Kuran-Text-Turkish").height(b + "px") : a > b && $("#Kuran-Text").height(a + "px"))
}
function GetCatalog() {
    $.post("KuranHandler.ashx?getCatalog=all", function (a) {
        $("#CatalogList").empty(); var b = '<div id="CatalogResultList-nav" class="listNav"></div><ul id="CatalogResultList" class="CatalogResultList">'; $.each(a, function (a, d) { b += '<li class="CatalogResultListItem"><div onclick=\'javascript:SearchCatalog(' + d.CatalogIndexId + ', "' + d.CatalogText + "\")'>" + d.CatalogText + "</div></li>" }); b += "</ul>"; $("#CatalogList").html(b); $("#CatalogResultList").listnav({
            initLetter: "a", includeAll: !1, includeOther: !0,
            flagDisabled: !1, noMatchText: "Kay\u0131t bulunamad\u0131.", showCounts: !1
        })
    }, "json")
}
function SearchCatalog(a, b) {
    var c = new Date; "" != b && ($("#MainTab").tabs("enable", 1), $("#MainTab").tabs("option", "selected", 1), $.post("KuranHandler.ashx?searchCatalog=" + a, function (a) {
        var e = (new Date - c) / 1E3; $("#Search-Result").empty(); $("#Search-Text").html("Konu: <b>" + b + "</b>"); $("#Search-Result-Count").html("<b>" + a.length + "</b> sonu\u00e7 (" + e + " saniye)"); var f = '<ul class="SearchResultList">'; $.each(a, function (a, b) {
            f += '<li class="SearchResultListItem"><div onclick=\'javascript:GetSearchResult(' + b.SureId +
            "," + b.AyetId + "," + b.LanguageId + ")' class='Search-Result-Item'><span class='Search-Result-Item-Header'>" + b.SureId + ". Sure (" + b.SureName + " Suresi), " + b.AyetId + ". Ayet</span><br /><span class='Search-Result-Item-Content'>" + b.AyetText + "</span></div></li>"
        }); f += "</ul>"; $("#Search-Result").html(f); $(".SearchResultList").easyPaginate({ step: 10 })
    }, "json"))
};


////http://kuran.diyanet.gov.tr/KuranHandler.ashx?l=tefsir&lid=2&a=101:1